# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0002_auto_20171015_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorlist',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='liquorlist',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
