# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0003_auto_20171016_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorlist',
            name='type',
            field=models.CharField(default='bottle', max_length=150),
        ),
    ]
