# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0004_liquorlist_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquorlist',
            old_name='type',
            new_name='can_or_bottle',
        ),
    ]
