# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0005_auto_20171016_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquorlist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
