# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0008_liquorlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquorlist',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
